# Generated by Django 5.0.6 on 2024-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_spec', models.TextField()),
                ('cat_image', models.ImageField(default='default_image.jpg', upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_image', models.ImageField(default='default_image.jpg', upload_to='products')),
                ('pro_amount', models.IntegerField()),
            ],
        ),
    ]
