# Generated by Django 5.0.6 on 2024-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('cat_spec', models.TextField()),
                ('cat_image', models.ImageField(blank=True, upload_to='category')),
            ],
        ),
    ]
