# Generated by Django 5.0.6 on 2024-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(default=1, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True),
        ),
    ]
