# Generated by Django 5.0.6 on 2024-07-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_products_alter_category_cat_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default=1, max_length=200, unique=True)),
                ('slug', models.SlugField(default=1, max_length=250, unique=True)),
                ('pro_des', models.TextField(blank=True)),
                ('pro_image', models.ImageField(blank=True, upload_to='products')),
                ('pro_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
        ),
    ]
